-- ASSET 테이블 생성 스크립트 (이미 존재한다면 DROP TABLE IF EXISTS 추가하여 초기화)
DROP TABLE IF EXISTS asset;

CREATE TABLE asset (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id VARCHAR(255),
                       name VARCHAR(255),
                       type VARCHAR(255),
                       quantity DECIMAL(19, 2),
                       purchase_price DECIMAL(19, 2),
                       current_price DECIMAL(19, 2)
);

-- 기존 INSERT 문은 그대로 두세요
INSERT INTO asset (user_id, name, type, quantity, purchase_price, current_price) VALUES
('ryan', 'Apple Inc. (AAPL)', 'Stock', 10, 150.00, 170.50),
('Ariana', 'Microsoft Corp. (MSFT)', 'Stock', 5, 250.00, 275.25),
('Yerin', 'U.S. Treasury Bond 2030', 'Bond', 1, 1000.00, 980.00),
('Jinro', 'S&P 500 Index Fund', 'Mutual Fund', 20, 50.00, 55.75);